import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),stage=$('stage'),voice=$('voice');
let modelPromise=null,ar=null,renderer=null,scene=null,camera=null,mode=null,active=false,run=0;
function loadModel(){if(!modelPromise)modelPromise=new GLTFLoader().loadAsync('./assets/lamya.glb').then(g=>{const box=new THREE.Box3().setFromObject(g.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());g.scene.position.sub(center);const group=new THREE.Group();group.add(g.scene);group.scale.setScalar(1/size.y);return group;}).catch(e=>{modelPromise=null;throw e});return modelPromise.then(m=>m.clone(true));}
function lighting(r){r.outputEncoding=THREE.sRGBEncoding;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=.9;}
function lights(s){s.add(new THREE.HemisphereLight(0xffffff,0x809794,.8));const l=new THREE.DirectionalLight(0xffffff,1.2);l.position.set(1,3,3);s.add(l);}
function text(s){$('status').textContent=s;}
function stop(){run++;active=false;voice.pause();voice.currentTime=0;$('listen').textContent='استمعي إلى قصتي';if(renderer){renderer.setAnimationLoop(null);renderer.dispose();}if(ar){try{ar.stop()}catch(e){}}stage.querySelectorAll('video').forEach(v=>v.srcObject?.getTracks().forEach(t=>t.stop()));ar=null;renderer=null;stage.replaceChildren();stage.hidden=true;$('hud').hidden=true;$('welcome').hidden=false;document.body.classList.remove('preview-mode');$('start').disabled=false;$('preview').disabled=false;mode=null;}
async function start(preview){const token=++run;mode=preview?'preview':'ar';$('initialStatus').textContent='';$('start').disabled=true;$('preview').disabled=true;try{
if(!preview&&!navigator.mediaDevices?.getUserMedia)throw new Error('الكاميرا تحتاج رابط HTTPS ومتصفحًا يدعمها. افتحي الرابط في Safari أو Chrome.');
$('welcome').hidden=true;stage.hidden=false;$('hud').hidden=false;$('listen').disabled=true;text('جارٍ تحميل المجسم…');
const model=await loadModel();if(token!==run)return;
if(preview){document.body.classList.add('preview-mode');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);stage.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.01,100);camera.position.set(0,0,2.4);lighting(renderer);lights(scene);scene.add(model);active=true;text('عرض ثلاثي الأبعاد • اسحبي لتدوير الشخصية');let drag=false,last=0;stage.addEventListener('pointerdown',e=>{drag=true;last=e.clientX});stage.addEventListener('pointerup',()=>drag=false);stage.addEventListener('pointercancel',()=>drag=false);stage.addEventListener('pointermove',e=>{if(drag){model.rotation.y+=(e.clientX-last)*.008;last=e.clientX}});renderer.setAnimationLoop(()=>renderer.render(scene,camera));}
else {text('جارٍ فتح الكاميرا…');const {MindARThree}=await import('./vendor/mindar-image-three.prod.js');if(token!==run)return;ar=new MindARThree({container:stage,imageTargetSrc:'./assets/lamya.mind',maxTrack:1,uiLoading:'no',uiScanning:'no',uiError:'no'});({renderer,scene,camera}=ar);lighting(renderer);lights(scene);const anchor=ar.addAnchor(0);model.scale.multiplyScalar(1.45);model.position.set(0,0,.18);anchor.group.add(model);anchor.onTargetFound=()=>{active=true;$('listen').disabled=false;text('ظهرت لمياء • اضغطي للاستماع');};anchor.onTargetLost=()=>{active=false;voice.pause();$('listen').textContent='تابعي الاستماع';$('listen').disabled=true;text('وجّهي الكاميرا إلى صورة لمياء على البطاقة');};await ar.start();if(token!==run){ar?.stop();return}text('وجّهي الكاميرا إلى صورة لمياء على البطاقة');renderer.setAnimationLoop(()=>renderer.render(scene,camera));}
$('listen').disabled=!active;
}catch(e){console.error(e);stop();$('initialStatus').textContent=/denied|permission|NotAllowed/i.test(e.message)?'لم يُسمح بالكاميرا. اسمحي بها من إعدادات المتصفح، ثم أعيدي المحاولة.':'تعذّر بدء التجربة. تحققي من الإنترنت، وافتحي الرابط في Safari أو Chrome. يمكنكِ تجربة عرض المجسم دون كاميرا.';}}
$('start').onclick=()=>start(false);$('preview').onclick=()=>start(true);$('back').onclick=stop;$('listen').onclick=async()=>{if(!active)return;if(voice.paused){try{await voice.play();$('listen').textContent='إيقاف مؤقت'}catch(e){text('تعذّر تشغيل الصوت. اضغطي للاستماع مجددًا.')}}else{voice.pause();$('listen').textContent='تابعي الاستماع'}};voice.onended=()=>{$('listen').textContent='استمعي مرة أخرى';voice.currentTime=0};document.addEventListener('visibilitychange',()=>{if(document.hidden){voice.pause();$('listen').textContent='تابعي الاستماع'}});window.addEventListener('pagehide',stop);window.addEventListener('resize',()=>{if(mode==='preview'&&renderer){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}});
